# Users | Passwords
zabbix_db_user: 'zabbix'
zabbix_db_pass: 'zabbix'

# Packages
common_pkgs:
      - net-tools
      - wget
      - curl
      - vim
      - htop
      - rpm
zabbix_deps_pkgs:
  - httpd
  - mariadb
  - mariadb-server
  - python2
  - python2-PyMySQL
  - python2-pip
zabbix_frontend_pkgs:
  - zabbix-web-mysql-scl
  - zabbix-apache-conf-scl
zabbix_install_pkgs:
  - zabbix-server-mysql
  - zabbix-agent
  - centos-release-scl

# Commands
zabbix_repo_cmd: rpm -Uvh https://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-release-5.0-1.el7.noarch.rpm
yum_clean_cache: yum clean all
import_schema_cmd: zcat /usr/share/doc/zabbix-server-mysql*/create.sql.gz | mysql -uzabbix -p zabbix

# Paths
zabbix_repo_path: /etc/yum.repos.d/zabbix.repo
zabbix_repo_src_path: ~/zabbix/roles/dependencies/templates/zabbix.repo.j2
zabbix_schema_path: /usr/share/doc/zabbix-server-mysql-5.0.24/create.sql.gz 


zabbix_server_path: /etc/zabbix/zabbix_server.conf
zabbix_php_path: /etc/opt/rh/rh-php72/php-fpm.d/zabbix.conf

# Services
zabbix_services: 
  - zabbix-server
  - zabbix-agent
  - httpd
  - rh-php72-php-fpm

