- name: Update and Install Common Pkgs
  block:
  - name: Update
    yum:
      name: "*"
      # exclude: kernel*
      state: latest

  - name: Enable EPEL Repo
    yum: 
      name: epel-release
      state: latest

  - name: Install
    yum:
      name: "{{ common_pkgs }}"
      state: latest
  become: true
