---

# Zabbix
- name: Install and configure Zabbix 
  block:
    - name: Zabbix deps
      yum:
        name: '{{ zabbix_deps_pkgs }}'
        state: latest

    - name: Install pexpect
      pip:
        name: pexpect

    - name: Restart MariaDB
      systemd:
        name: mariadb
        state: restarted
        enabled: yes

    - name: Enable Zabbix repo
      shell: '{{ zabbix_repo_cmd }}'
      args:
        warn: false
      ignore_errors: true
      register: zabbix_repo_out

    - debug:
        var: zabbix_repo_out.stdout_lines

    - name: Clear All cached info
      shell: '{{ yum_clean_cache }}' 
      args:
        warn: false
      ignore_errors: true
      register: yum_clean_cache_out

    - debug:
        var: yum_clean_cache_out.stdout_lines

    # - name: Enable Zabbix repo
    #   yum_repository:
    #     name: zabbix
    #     description: Zabbix Official Repository
    #     baseurl: https://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-release-5.0-1.el7.noarch.rpm 

    - name: Install Zabbix server | agent | frontend 
      yum:
        name: '{{ zabbix_install_pkgs }}'
        state: present

    - name: Enable zabbix-frontend repo
      template:
        src: '{{ zabbix_repo_src_path }}'
        dest: '{{ zabbix_repo_path }}'
        owner: root

    # - name: Enable zabbix-frontend repo
    #   replace:
    #     path: '{{ zabbix_repo_path }}'
    #     after: "[zabbix-frontend]"
    #     before: "[zabbix-debuginfo]"
    #     regexp: "enabled=0"
    #     replace: "enabled=1"

    - name: Install Zabbix frontend
      yum:
        name: '{{ zabbix_frontend_pkgs }}'
        state: latest
  become: true

# MariaDB
- name: Configure MariaDB for Zabbix server
  block:
    - name: Create zabbix database
      mysql_db:
        name: zabbix
        state: present
        encoding: utf8
        collation: utf8_bin

    - name: Create zabbix user
      mysql_user:
        name: '{{ zabbix_db_user }}'
        password: '{{ zabbix_db_pass }}' 
        state: present
        priv: '*.*:ALL'

    - name: Import initial schema and data
      expect:
        command: '{{ import_schema_cmd }}'
        responses: 
          password: '{{ zabbix_db_pass }}'
      tags: schema

    - name: Configure database for zabbix server
      replace:
        path: '{{ zabbix_server_path }}'
        after: "DBUser=zabbix"
        before: "DBPassword=zabbix"
        regex: "#DBPassword=zabbix"
        replace: "DBPassword=zabbix"
  become: true

# PHP
- name: Configure PHP for Zabbix frontend
  block:
    - name: Edit timezone
      replace:
        path: '{{ zabbix_php_path }}'
        after: "php_value[max_input_vars] = 10000"
        regex: ";php_value[date.timezone] = Europe/Riga"
        replace: "php_value[date.timezone] = America/Sao_Paulo"
  become: true

- name: Post-Installation
  block:
  - name: Restart Zabbix processes
    systemd:
      name: '{{ zabbix_services }}'
      state: restarted
      enabled: yes
  become: true

